baseURL = 'https://gregturner.com/'
languageCode = 'en-au'
title = 'Dr. Greg Turner'
theme = 'papermod'

# Papermod theme settings
[params]
showCodeCopyButtons = true
showReadingTime = true
custom_css = ["css/custom.css"]

[params.editPost]
URL = "https://github.com/cogat/til-blog/blob/main/content"
text = "Suggest Changes"
appendFilePath = true
